version: '3.1'

services:
  db:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "./db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
